version: "3.5"
# All parameters used are in .env file
services:
  a-lumen-blog-backend:
    image: fattureincloud/php:7.4-playground
    container_name: a-lumen-blog-backend
    environment:
      - XDEBUG_MODE=${XDEBUG_MODE}
    user: "www-data:www-data"
    volumes:
      # Code
      - .:/var/www/html:cached
      # container /tmp folder, used for profiler and other stuff
      - ./private/tmp:/tmp:cached
    ports:
      - ${PHP_HOST_PORT}:80
    networks:
      backend:
        aliases:
          - a-lumen-blog-backend

  a-lumen-blog-db:
    image: mysql:8
    # !IMPORTANT!: This must be the same as DB_HOST variable in .env file
    container_name: a-lumen-blog-db
    volumes:
      # Persistent DB data
      - a-lumen-blog-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - ${MYSQL_HOST_PORT}:3306
    networks:
      backend:
        aliases:
          - a-lumen-blog-db

volumes:
  a-lumen-blog-db-data:
    driver: local

networks:
  backend:
    name: a-lumen-blog-network
